### ISSUE TITLE
JupyterHub Kernel Picker Not Showing Up Anymore

### ISSUE THREAD

**Issue by mtreca** [microsoft/vscode-jupyter-hub#44]
## Environment data

-   VS Code version: VSCodium 1.85.1
-   JupyterHub Extension version (available under the Extensions sidebar): v2023.10.1003492320
-  Jupyter Extension version: v2023.9.100
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: Mac

## Expected behaviour

The JupyterHub specific kernel picker used to show up, which allows me to connect to a remote JH instance.

## Actual behaviour

No kernel picker. Instead I get the base kernel picker from the Jupyter extension, but trying to connect results in an error (due to the absence of JH-specific logic?)

<img width="625" alt="Screenshot 2023-12-28 at 17 51 29" src="https://github.com/microsoft/vscode-jupyter-hub/assets/16440823/5c9396f6-a4b9-4f35-b640-50367ef5fb75">

## Logs

No logs from the JH extension, almost as if it wasn't activating

**Comment by DonJayamanne** [comment]
Sorry for not getting back to you on this, are you still running into this issue.
Note: Ples ensure you install the latest version of Jupyter extension ( you have an old version installed)

**Comment by mtreca** [comment]
Hey there. Thanks for the followup. I cannot reproduce this one after updating, so I think you were right. Closing.
