### ISSUE TITLE
Publish Extension on OpenVSX

### ISSUE THREAD

**Issue by mtreca** [microsoft/vscode-jupyter-hub#50]
It seems that this extension is not yet present on the [OpenVSX](https://open-vsx.org/) repository. Given that some companies require packages to be present there to allow their installation, would it be possible to make the extension available there? I would add it myself but I do not think I can.

Let me know if I can help in that regard!

**Comment by isidorn** [comment]
Thanks for opening this feature request but after thinking this over we have decided to not proceed with supporting Open VSIX. Having to support another Marketplace would also mean needing to directly support that Marketplace's users and we are not prepared to take on that increase support requirements of supporting e.g. Theia.

That being said, the extension is and will continue to be open source, and so anyone wanting to upload their own VSIX is welcome to do so as long as the MIT license is met.

**Comment by mtreca** [comment]
Thanks for the reply, will look into seeing if I can do this myself.
