### ISSUE TITLE
Can't connect to remote jupyterhub

### ISSUE THREAD

**Issue by liudaolunboluo** [microsoft/vscode-jupyter-hub#62]
I use jupyterHub spawners;i'm sure my username and password can login jupyterhub

## Environment data

- VS Code version:  1.91.1 (Universal)
- Jupyter Extension version (available under the Extensions sidebar): Switch to Pre-Release Version
- Python Extension version (available under the Extensions sidebar): Switch to Pre-Release Version
- OS (Windows | Mac | Linux distro) and version: mac
- Python and/or Anaconda version: 3.10
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Jupyter server running: Remote

## Expected behaviour

Connect jupyterhub session via vscode jupyterhub extension.

## Actual behaviour

Invalid username or password.

## Steps to reproduce:

[NOTE: Self-contained, minimal reproducing code samples are extremely helpful and will expedite addressing your issue]

As described in the doc.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
15:02:01.553 [error] Failed to start the Jupyter Server Error: Failed to fetch user info, Internal Server Error (500) with message  {"status": 500, "message": "error"}
    > at startServer (/Users/zhangyunfan/.vscode/extensions/ms-toolsai.jupyter-hub-2024.4.100/dist/extension.node.js:67004:9)
15:02:11.988 [error] Timeout waiting for Jupyter Server to start, current status = null
15:02:12.845 [error] SessionManager cannot enumerate kernelSpecs. Specs undefined.
15:02:12.846 [error] Uri verification error Error: Failed to enumeration kernel Specs
    > at /Users/zhangyunfan/.vscode/extensions/ms-toolsai.jupyter-hub-2024.4.100/dist/extension.node.js:67150:21
```

</p>
</details>

**Comment by liudaolunboluo** [comment]
I should konw the reason
this code:
<img width="973" alt="image" src="https://github.com/user-attachments/assets/10680d61-d9b8-4677-bc89-e1a487699550">

Use the user server attribute to determine if the user has any services started
But in JupyterHub there is a case where this user has multiple services, and his attribute servers has a value, while server is null：
```json
{
    "kind": "user",
    "name": "admin",
    "admin": true,
    "groups": [],
    "server": null,
    "pending": null,
    "created": "2023-04-17T03:35:54Z",
    "last_activity": "2024-07-25T08:37:01.166163Z",
    "servers": {
        "265": {
            "name": "265",
            "last_activity": "2024-07-25T07:48:46Z",
            "started": "2024-07-25T07:47:05Z",
            "pending": null,
            "ready": true,
            "state": {
                "pod_name": "jupyter-admin--265"
            },
            "url": "/jupyter/user/admin/265/",
            "user_options": {},
            "progress_url": "/jupyter/hub/api/users/admin/servers/265/progress"
        }
    },
    "auth_state": null
}
```

**Comment by DonJayamanne** [comment]
>  [error] Failed to start the Jupyter Server Error: Failed to fetch user info, Internal Server Error (500) with message  {"status": 500, "message": "error"}

> But in JupyterHub there is a case where this user has multiple services, and his attribute servers has a value, while server is null：

Oh thanks, thats useful in hardening this code.
However in this intance, thats not whats causing the problem,
If you have a look, the error is being loggec at ````traceError(`Failed to get user```, and the error is `nternal Server Error (500) with message  {"status": 500, "message": "error"}`
Basically the HTTP request is failing due to an error on the server side with 500 status code.

**Comment by DonJayamanne** [comment]
Please can you check the Jupyter Hub logs to see what requests were sent and the errors (generally this will be logged in the terminal when you enable logging for Jupyter Hub)

**Comment by liudaolunboluo** [comment]
> Please can you check the Jupyter Hub logs to see what requests were sent and the errors (generally this will be logged in the terminal when you enable logging for Jupyter Hub)

yes,I see my jupyter log,it's throw excetion,because it start default jupyter server error

but I want to connect other jupyter server,for exmple: I start two jupyter server:default and name "test1" serer,now I can only connect deafult server.

**Comment by DonJayamanne** [comment]
Thank you very much, 
Closing this issue in favour of https://github.com/microsoft/vscode-jupyter-hub/issues/39

**Comment by liudaolunboluo** [comment]
> Thank you very much, Closing this issue in favour of #39

Is there a release plan for this requirement?

**Comment by DonJayamanne** [comment]
> Is there a release plan for this requirement?

Unfortunately no, we priority issues based on community feedback (upvotes & the like)
