### ISSUE TITLE
Unable to execute code in JupyterHub

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter-hub#64]
Some time in the past few months JupyterLab installed/configured via JupyterHuab is always using the latest WebSocket prortocol.
Fix will be here https://github.com/microsoft/vscode-jupyter/issues/14422
Attempted changes here https://github.com/microsoft/vscode-jupyter/pull/15897 & here https://github.com/microsoft/vscode-notebook-renderers/pull/208/files

**Work around**

Try overriding this value to ensure its an empty string to use the old protocol
Docs here https://jupyter-server.readthedocs.io/en/latest/other/full-config.html

```
--ServerApp.kernel_ws_protocol=<Unicode>
    DEPRECATED. Use ZMQChannelsWebsocketConnection.kernel_ws_protocol

BaseKernelWebsocketConnection.kernel_ws_protocolUnicode
Default: None

Preferred kernel message protocol over websocket to use (default: None). If an empty string is passed, select the legacy protocol. If None, the selected protocol will depend on what the front-end supports (usually the most recent protocol supported by the back-end and the front-end).
```

**Comment by jaymc-arg** [comment]
@DonJayamanne Hi again.
Where do i have to set this configuration? can't find it [here](https://jupyterhub.readthedocs.io/en/stable/reference/api/app.html). Is it for jupyter server? how can I set it to jupyter hub?

**Comment by basiekjusz** [comment]
I'm also encountering this issue, however the workaround does not solve it at all.

**Comment by Yelinz** [comment]
So there is no workaround if you do not have configuration permission for the jupyterLab server?

**Comment by basiekjusz** [comment]
I have access to the configuration, however overriding these values didn't help at all.

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter-hub/issues/67
