### ISSUE TITLE
Local files auto sync

### ISSUE THREAD

**Issue by hermaneyd** [microsoft/vscode-jupyter-hub#76]
Hi,

I would like to be able to sync files between local machine and Jupyter Hub. For example, I have a Jupyter Notebook and a local Python module (package/file) that I want to import into that Notebook and it's very inconvenient to upload a local file into Jupyter Hub via the Web UI. It would be better if the plugin had a feature to upload files manually or automatically (based on imports in Notebook code).

Is it possible to implement this or maybe someone knows a more friendly workaround?

Thanks!

**Comment by DonJayamanne** [comment]
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1601
